version: '3.7'

services:

  db:
    container_name: bmaindb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: hapipoc
      POSTGRES_USER: hapipoc
      POSTGRES_DB: hapi
    # not needed for networking between containers but here for troubleshooting
    ports:
      - "5433:5432"

  fhir:
    container_name: bmainfhir
    image: hapiproject/hapi:latest
    ports:
      - "8081:8080"
    environment:
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://bmaindb:5432/hapi'
      spring.datasource.username: hapipoc
      spring.datasource.password: hapipoc
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      spring.jpa.properties.hibernate.search.enabled: false
    depends_on:
      - db
