version: '3.7'

services:

  db:
    container_name: fhirdb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: hapipoc
      POSTGRES_USER: hapipoc
      POSTGRES_DB: hapi
    # not needed for networking between containers but here for troubleshooting
    ports:
      - "5432:5432"

  fhir:
    container_name: fhir
    image: hapiproject/hapi:latest
    ports:
      - "8081:8080"
    environment:
      HAPI_FHIR_USERNAME : admin
      HAPI_FHIR_PASSWORD : admin
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://bmaindb:5432/hapi'
      spring.datasource.username: hapipoc
      spring.datasource.password: hapipoc
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      spring.jpa.properties.hibernate.search.enabled: false
      
      hapi.fhir.ig_runtime_upload_enabled: true
      hapi.fhir.ips_enabled: true
      #hapi.fhir.implementationguides.ips_1_1_0.packageUrl: https://build.fhir.org/ig/HL7/fhir-ips/package.tgz
      #hapi.fhir.implementationguides.ips_1_1_0.name: hl7.fhir.uv.ips
      #hapi.fhir.implementationguides.ips_1_1_0.version: 1.1.0
      #hapi.fhir.implementationguides.ips_1_1_0.supported_resource_types: Patient

    depends_on:
      - db
...